"""
Advanced re-analysis of the Scenario 6 mission
===============================================

This script operates on the *real* data already produced by the framework
(``results/s6_kursa_kludas_analize.csv``, the 600 s / 50 Hz complex mission)
and turns it into the layered analysis the thesis is missing:

  * aggregate tracking metrics per controller,
  * a steady-state vs transient decomposition,
  * a per-segment breakdown localised to each manoeuvre,
  * the empirical error distribution (heavy-tail diagnosis),
  * zoomed dissections of the two largest NMPC excursions,
  * a clean two-panel mission overview,

and writes a CSV + Markdown results report.  Nothing here re-runs a
simulation, so it has no CasADi / Fossen dependency.

All figure text uses config.T() so that LANGUAGE = "lv" in config.py produces
Latvian labels without editing this file.

Run:
    python -m analysis.analyze_s6
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

from analysis import metrics as M
from analysis import plotting as P
from analysis import report as R
from config import T

D2R = np.pi / 180.0
R2D = 180.0 / np.pi

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RESULTS = os.path.join(ROOT, "results")
OUTDIR = os.path.join(RESULTS, "advanced")

# Mission structure (mirrors experiments.run_remus100_comparison.scenario_6_complex)
WAYPOINTS = [(0, 0), (15, 0), (25, 90), (40, 90), (40, 200),
             (10, 200), (30, 330), (45, 45), (20, 0)]
SWITCH = [5, 60, 120, 180, 260, 340, 420, 500]
T_FINAL = 600.0
BOUNDS = [0.0] + SWITCH + [T_FINAL]

# Stable internal names → CSV column prefixes (generated by save_s6_heading_error_csv).
# Update these if controller names change in run_remus100_comparison.py.
CONTROLLERS = {
    "PID (tuned)":             "PID_tuned",
    "NMPC offset-free (N=30)": "NMPC_offset-free_N30",
}


def _ssa_deg(a):
    return (a + 180.0) % 360.0 - 180.0


def _turn_labels():
    labels = []
    for k in range(len(BOUNDS) - 1):
        if k == 0:
            labels.append(T("seg_holding"))
            continue
        turn = _ssa_deg(WAYPOINTS[k][1] - WAYPOINTS[k - 1][1])
        if abs(turn) < 1e-6:
            labels.append(T("seg_holding"))
        else:
            labels.append(f"{T('seg_turn')} {turn:+.0f}°")
    return labels


def load():
    df = pd.read_csv(os.path.join(RESULTS, "s6_kursa_kludas_analize.csv"))
    t = df["time_s"].values
    ref = df["reference_heading_continuous_deg"].values
    series = {
        name: df[f"{pfx}_heading_continuous_deg"].values
        for name, pfx in CONTROLLERS.items()
    }
    errs = {
        name: df[f"{pfx}_heading_error_deg"].values
        for name, pfx in CONTROLLERS.items()
    }
    return t, ref, series, errs


def main():
    os.makedirs(OUTDIR, exist_ok=True)
    t, ref_deg, series_deg, err_deg = load()
    ref_rad = ref_deg * D2R

    # ---- aggregate metrics ----
    agg_rows = []
    for name, sig in series_deg.items():
        tm = M.tracking_metrics(t, sig * D2R, ref_rad, angular=True)
        agg_rows.append({
            "controller": name,
            "rmse_deg": tm.rmse * R2D, "mae_deg": tm.mae * R2D,
            "iae_deg_s": tm.iae * R2D, "itae": tm.itae * R2D,
            "max_deg": tm.max_abs * R2D, "std_deg": tm.std * R2D,
        })

    # ---- transient vs steady ----
    changing = [WAYPOINTS[i + 1][1] != WAYPOINTS[i][1] for i in range(len(SWITCH))]
    split = {}
    for name, sig in series_deg.items():
        sp = M.split_transient_steady(t, sig * D2R, ref_rad, SWITCH,
                                      angular=True, transient_window=35.0,
                                      only_changing=changing)
        split[name] = {k: (v * R2D if "rmse" in k or "max" in k else v)
                       for k, v in sp.items()}

    # ---- three operating regimes: aggregate / transient / settled holding ----
    settled_mask = np.zeros(len(t), bool)
    for a, b in zip(BOUNDS[:-1], BOUNDS[1:]):
        settled_mask |= (t >= a + 0.6 * (b - a)) & (t < b)
    regimes = {}
    for name, sig in series_deg.items():
        e = M.angle_error(sig * D2R, ref_rad) * R2D
        regimes[name] = {
            T("regime_aggregate"): float(np.sqrt(np.mean(e ** 2))),
            T("regime_transient"): split[name]["transient_rmse"],
            T("regime_settled"):   float(np.sqrt(np.mean(e[settled_mask] ** 2))),
        }

    # ---- per-segment ----
    seg = {}
    for name, sig in series_deg.items():
        rows = M.segment_decompose(t, sig * D2R, ref_rad, BOUNDS,
                                   angular=True, steady_frac=0.4)
        for rrow in rows:
            for k in ("iae", "mae", "rmse", "max_abs", "steady_state"):
                rrow[k] *= R2D
        seg[name] = rows

    # ---------------- figures ----------------
    f1 = P.plot_regime_comparison(
        regimes, os.path.join(OUTDIR, "s6_regime_comparison.png"),
        title="Heading RMSE by regime: aggregate masks the regime switch")
    f2 = P.plot_segment_breakdown(
        seg, os.path.join(OUTDIR, "s6_segment_breakdown.png"),
        turn_labels=_turn_labels(), metric="iae", unit="°·s")
    f3 = P.plot_error_ecdf(
        {n: e for n, e in err_deg.items()},
        os.path.join(OUTDIR, "s6_error_ecdf.png"))
    f4 = P.plot_spike_zoom(
        t, series_deg, ref_deg, (490, 570),
        os.path.join(OUTDIR, "s6_zoom_reversal.png"),
        title="Sharp heading reversal overshoot (330°→45°→0°)",
        note="NMPC makes an aggressive initial manoeuvre and overshoots the target; "
             "tuned PID is slower but without a large overshoot.")
    f5 = P.plot_spike_zoom(
        t, series_deg, ref_deg, (255, 335),
        os.path.join(OUTDIR, "s6_zoom_depthcoupling.png"),
        title="Depth-coupling heading excursion (constant heading 200°)",
        note="Heading is constant (200°) in this segment, but depth changes 40→10 m. "
             "The reduced NMPC predictor ignores pitch→yaw coupling, so heading drifts "
             "during the ascent.")
    # mission overview with the two events annotated
    nmpc_name = next(n for n in err_deg if "NMPC" in n)
    i_rev = int(np.argmax(np.abs(err_deg[nmpc_name])))
    i_dep_region = (t >= 255) & (t <= 335)
    i_dep = np.where(i_dep_region)[0][np.argmax(np.abs(err_deg[nmpc_name][i_dep_region]))]
    f6 = P.plot_mission_overview(
        t, series_deg, ref_deg, err_deg, SWITCH,
        os.path.join(OUTDIR, "s6_mission_overview.png"),
        events=[
            (t[i_dep], err_deg[nmpc_name][i_dep],
             f"  depth coupling {err_deg[nmpc_name][i_dep]:+.0f}°"),
            (t[i_rev], err_deg[nmpc_name][i_rev],
             f"  reversal overshoot {err_deg[nmpc_name][i_rev]:+.0f}°"),
        ])

    # ---------------- reports ----------------
    R.write_csv(agg_rows,
                ["controller", "rmse_deg", "mae_deg", "iae_deg_s", "itae", "max_deg", "std_deg"],
                os.path.join(OUTDIR, "s6_summary_metrics.csv"))
    seg_csv_rows = []
    for name, rows in seg.items():
        for rrow in rows:
            seg_csv_rows.append({"controller": name, **rrow})
    R.write_csv(seg_csv_rows,
                ["controller", "start", "end", "iae", "mae", "rmse", "max_abs", "steady_state"],
                os.path.join(OUTDIR, "s6_segment_metrics.csv"))

    agg_md = R.metrics_table_md(
        agg_rows,
        ["controller", "rmse_deg", "mae_deg", "iae_deg_s", "max_deg"],
        headers=[T("col_controller"), "RMSE [°]", "MAE [°]", "IAE [°·s]", T("col_max_e")],
        nd=2)
    regime_rows = [
        {
            "controller": n,
            "aggregate": regimes[n][T("regime_aggregate")],
            "transient": regimes[n][T("regime_transient")],
            "settled":   regimes[n][T("regime_settled")],
        }
        for n in regimes
    ]
    split_md = R.metrics_table_md(
        regime_rows, ["controller", "aggregate", "transient", "settled"],
        headers=[T("col_controller"), T("col_aggregate_rmse"),
                 T("col_transient_rmse"), T("col_settled_rmse")], nd=3)

    ss_pid  = np.mean([s["steady_state"] for s in seg[list(seg)[0]]])
    ss_nmpc = np.mean([s["steady_state"] for s in seg[list(seg)[-1]]])
    ctrl0, ctrl1 = list(agg_rows[0]["controller"]), list(agg_rows[-1]["controller"])
    summary = (
        f"- **Aggregate heading RMSE:** "
        f"{agg_rows[0]['controller']} = {agg_rows[0]['rmse_deg']:.2f}°, "
        f"{agg_rows[-1]['controller']} = {agg_rows[-1]['rmse_deg']:.2f}° "
        f"— aggregate metric makes the second controller appear worse.\n"
        f"- **Steady-state holding error (mean across segments):** "
        f"{agg_rows[0]['controller']} = {ss_pid:.3f}°, "
        f"{agg_rows[-1]['controller']} = {ss_nmpc:.3f}° "
        f"— NMPC is ~{ss_pid/max(ss_nmpc, 1e-9):.0f}× more precise in holding.\n"
        f"- **Root cause:** aggregate RMSE is dominated by two transient events — "
        f"reversal overshoot (~{abs(err_deg[nmpc_name][i_rev]):.0f}°, "
        f"t≈{t[i_rev]:.0f} s) and depth-coupling excursion "
        f"(~{abs(err_deg[nmpc_name][i_dep]):.0f}°, t≈{t[i_dep]:.0f} s).\n"
    )

    R.write_markdown_report(
        os.path.join(OUTDIR, "s6_results.md"),
        "Scenario 6 in-depth analysis (heading tracking)",
        [
            ("Summary", summary),
            ("Aggregate metrics", agg_md),
            ("Tracking error by regime", split_md),
            ("Note", "All values from `s6_kursa_kludas_analize.csv` "
                     "(600 s, 50 Hz). Figures in `results/advanced/`."),
        ],
    )

    print("Saved figures:")
    for f in (f1, f2, f3, f4, f5, f6):
        print("  ", f)
    print("Saved data: s6_summary_metrics.csv, s6_segment_metrics.csv, s6_results.md")


if __name__ == "__main__":
    main()
