"""
Advanced re-analysis of the Scenario 6 mission
===============================================

This script operates on the *real* data already produced by the framework
(``results/s6_kursa_kludas_analize.csv``, the 600 s / 50 Hz complex mission)
and turns it into the layered analysis the thesis is missing:

  * aggregate tracking metrics per controller,
  * a steady-state vs transient decomposition,
  * a per-segment breakdown localised to each manoeuvre,
  * the empirical error distribution (heavy-tail diagnosis),
  * zoomed dissections of the two largest NMPC excursions,
  * a clean two-panel mission overview,

and writes a CSV + Markdown results report.  Nothing here re-runs a
simulation, so it has no CasADi / Fossen dependency.

Each figure is produced for BOTH tracked channels: heading (default file names)
and depth (``*_dzilums`` file names).  The depth half needs the depth columns
that ``save_s6_error_csv`` writes; older CSVs without them still work, the
depth figures are simply skipped.

All figure text uses config.T() so that LANGUAGE = "lv" in config.py produces
Latvian labels without editing this file.

Run:
    python -m analysis.analyze_s6
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

from analysis import metrics as M
from analysis import plotting as P
from analysis import report as R
from config import T

D2R = np.pi / 180.0
R2D = 180.0 / np.pi

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RESULTS = os.path.join(ROOT, "results")
OUTDIR = os.path.join(RESULTS, "advanced")

# Mission structure (mirrors experiments.run_remus100_comparison.scenario_6_complex)
WAYPOINTS = [(0, 0), (15, 0), (25, 90), (40, 90), (40, 200),
             (10, 200), (30, 330), (45, 45), (20, 0)]
SWITCH = [5, 60, 120, 180, 260, 340, 420, 500]
T_FINAL = 600.0
BOUNDS = [0.0] + SWITCH + [T_FINAL]

# Stable internal names → CSV column prefixes (generated by save_s6_error_csv).
# Update these if controller names change in run_remus100_comparison.py.
CONTROLLERS = {
    "Fossen PID/SMC":          "Fossen_PID/SMC",
    "PID (tuned)":             "PID_tuned",
    "NMPC offset-free (N=12)": "NMPC_offset-free_N12",
}


def _ssa_deg(a):
    return (a + 180.0) % 360.0 - 180.0


def _turn_labels():
    labels = []
    for k in range(len(BOUNDS) - 1):
        if k == 0:
            labels.append(T("seg_holding"))
            continue
        turn = _ssa_deg(WAYPOINTS[k][1] - WAYPOINTS[k - 1][1])
        if abs(turn) < 1e-6:
            labels.append(T("seg_holding"))
        else:
            labels.append(f"{T('seg_turn')} {turn:+.0f}°")
    return labels


def _depth_labels():
    """Per-segment labels for the depth channel: the commanded depth change."""
    labels = []
    for k in range(len(BOUNDS) - 1):
        if k == 0:
            labels.append(T("seg_holding"))
            continue
        dz = WAYPOINTS[k][0] - WAYPOINTS[k - 1][0]
        labels.append(T("seg_holding") if abs(dz) < 1e-6 else f"{dz:+.0f} m")
    return labels


def _changing(index: int):
    """One bool per switch: did this segment actually command a change?

    ``index`` selects the waypoint component — 0 = depth, 1 = heading.  Pure
    holds must not be scored as transients, and a turn is not a depth
    manoeuvre, so each channel gets its own mask.
    """
    return [WAYPOINTS[i + 1][index] != WAYPOINTS[i][index] for i in range(len(SWITCH))]


def load():
    """Load the scenario-6 time series.

    Returns ``(t, heading, depth)``; each channel is a dict of ref / series /
    errs.  ``depth`` is None for CSVs written before the depth columns existed.
    """
    df = pd.read_csv(os.path.join(RESULTS, "s6_kursa_kludas_analize.csv"))
    t = df["time_s"].values
    heading = {
        "ref": df["reference_heading_continuous_deg"].values,
        "series": {name: df[f"{pfx}_heading_continuous_deg"].values
                   for name, pfx in CONTROLLERS.items()},
        "errs": {name: df[f"{pfx}_heading_error_deg"].values
                 for name, pfx in CONTROLLERS.items()},
    }

    depth_cols = ["reference_depth_m"]
    for pfx in CONTROLLERS.values():
        depth_cols += [f"{pfx}_depth_m", f"{pfx}_depth_error_m"]
    if not all(c in df.columns for c in depth_cols):
        print("  [analyze_s6] no depth columns in the CSV — rerun "
              "experiments.run_remus100_comparison to get the depth figures")
        return t, heading, None

    depth = {
        "ref": df["reference_depth_m"].values,
        "series": {name: df[f"{pfx}_depth_m"].values
                   for name, pfx in CONTROLLERS.items()},
        "errs": {name: df[f"{pfx}_depth_error_m"].values
                 for name, pfx in CONTROLLERS.items()},
    }
    return t, heading, depth


def analyse_channel(t, series, ref, changing, *, angular, scale=1.0):
    """Aggregate / transient-steady / regime / per-segment metrics for a channel.

    ``series`` and ``ref`` are in the channel's native unit (rad for heading,
    m for depth); ``scale`` converts every reported figure into the display
    unit (R2D for heading, 1.0 for depth).
    """
    agg_rows = []
    for name, sig in series.items():
        tm = M.tracking_metrics(t, sig, ref, angular=angular)
        agg_rows.append({
            "controller": name,
            "rmse": tm.rmse * scale, "mae": tm.mae * scale,
            "iae": tm.iae * scale, "itae": tm.itae * scale,
            "max": tm.max_abs * scale, "std": tm.std * scale,
        })

    split = {}
    for name, sig in series.items():
        sp = M.split_transient_steady(t, sig, ref, SWITCH, angular=angular,
                                      transient_window=35.0, only_changing=changing)
        split[name] = {k: (v * scale if "rmse" in k or "max" in k else v)
                       for k, v in sp.items()}

    # Settled = last 40% of every segment, i.e. after the manoeuvre has decayed.
    settled_mask = np.zeros(len(t), bool)
    for a, b in zip(BOUNDS[:-1], BOUNDS[1:]):
        settled_mask |= (t >= a + 0.6 * (b - a)) & (t < b)
    regimes = {}
    for name, sig in series.items():
        e = (M.angle_error(sig, ref) if angular else (sig - ref)) * scale
        regimes[name] = {
            T("regime_aggregate"): float(np.sqrt(np.mean(e ** 2))),
            T("regime_transient"): split[name]["transient_rmse"],
            T("regime_settled"):   float(np.sqrt(np.mean(e[settled_mask] ** 2))),
        }

    seg = {}
    for name, sig in series.items():
        rows = M.segment_decompose(t, sig, ref, BOUNDS, angular=angular,
                                   steady_frac=0.4)
        for rrow in rows:
            for k in ("iae", "mae", "rmse", "max_abs", "steady_state"):
                rrow[k] *= scale
        seg[name] = rows

    return agg_rows, split, regimes, seg


def main():
    os.makedirs(OUTDIR, exist_ok=True)
    t, heading, depth = load()
    ref_deg, series_deg, err_deg = heading["ref"], heading["series"], heading["errs"]
    ref_rad = ref_deg * D2R

    # ---- heading channel: aggregate / transient-steady / regimes / segments ----
    agg_rows, split, regimes, seg = analyse_channel(
        t, {n: sig * D2R for n, sig in series_deg.items()}, ref_rad,
        _changing(1), angular=True, scale=R2D)
    # Keep the historical unit-suffixed keys for the heading CSV / tables.
    agg_rows = [{"controller": r["controller"], "rmse_deg": r["rmse"],
                 "mae_deg": r["mae"], "iae_deg_s": r["iae"], "itae": r["itae"],
                 "max_deg": r["max"], "std_deg": r["std"]} for r in agg_rows]

    # ---------------- figures ----------------
    # Every figure is written twice: the default name, and a variant with the
    # Fossen baseline toggled the other way (suffix "_bez_fossen" = without,
    # "_ar_fossen" = with).  Defaults: with Fossen everywhere except the
    # zooms, where its tens-of-degrees error would flatten the other curves.
    FOSSEN = "Fossen PID/SMC"

    def _no_f(d):
        return {k: v for k, v in d.items() if k != FOSSEN}

    f1 = P.plot_regime_comparison(
        regimes, os.path.join(OUTDIR, "s6_regime_comparison.png"),
        title=T("s6_regime_title"))
    P.plot_regime_comparison(
        _no_f(regimes), os.path.join(OUTDIR, "s6_regime_comparison_bez_fossen.png"),
        title=T("s6_regime_title"))
    f2 = P.plot_segment_breakdown(
        seg, os.path.join(OUTDIR, "s6_segment_breakdown.png"),
        turn_labels=_turn_labels(), metric="iae", unit="°·s")
    P.plot_segment_breakdown(
        _no_f(seg), os.path.join(OUTDIR, "s6_segment_breakdown_bez_fossen.png"),
        turn_labels=_turn_labels(), metric="iae", unit="°·s")
    f3 = P.plot_error_ecdf(
        dict(err_deg), os.path.join(OUTDIR, "s6_error_ecdf.png"))
    P.plot_error_ecdf(
        _no_f(err_deg), os.path.join(OUTDIR, "s6_error_ecdf_bez_fossen.png"))
    f4 = P.plot_spike_zoom(
        t, _no_f(series_deg), ref_deg, (495, 560),
        os.path.join(OUTDIR, "s6_zoom_reversal.png"),
        title=T("s6_zoom_rev_title"))
    P.plot_spike_zoom(
        t, series_deg, ref_deg, (495, 560),
        os.path.join(OUTDIR, "s6_zoom_reversal_ar_fossen.png"),
        title=T("s6_zoom_rev_title"))
    f5 = P.plot_spike_zoom(
        t, _no_f(series_deg), ref_deg, (255, 310),
        os.path.join(OUTDIR, "s6_zoom_depthcoupling.png"),
        title=T("s6_zoom_depth_title"))
    P.plot_spike_zoom(
        t, series_deg, ref_deg, (255, 310),
        os.path.join(OUTDIR, "s6_zoom_depthcoupling_ar_fossen.png"),
        title=T("s6_zoom_depth_title"))
    f6 = P.plot_mission_overview(
        t, series_deg, ref_deg, err_deg, SWITCH,
        os.path.join(OUTDIR, "s6_mission_overview.png"))
    P.plot_mission_overview(
        t, _no_f(series_deg), ref_deg, _no_f(err_deg), SWITCH,
        os.path.join(OUTDIR, "s6_mission_overview_bez_fossen.png"))

    # ---------------- depth channel ----------------
    # The same four decompositions applied to depth, written as "*_dzilums".
    # Depth deserves the same treatment as heading: the aggregate depth RMSE
    # is likewise dominated by the dive/climb transients and says nothing about
    # how well a controller *holds* a commanded depth.
    depth_figs = []
    if depth is not None:
        d_agg, d_split, d_regimes, d_seg = analyse_channel(
            t, depth["series"], depth["ref"], _changing(0),
            angular=False, scale=1.0)
        d_err = depth["errs"]

        depth_figs.append(P.plot_regime_comparison(
            d_regimes, os.path.join(OUTDIR, "s6_regime_comparison_dzilums.png"),
            unit="m", ylabel=T("rmse_log_m"), title=T("s6_regime_depth_title")))
        P.plot_regime_comparison(
            _no_f(d_regimes),
            os.path.join(OUTDIR, "s6_regime_comparison_dzilums_bez_fossen.png"),
            unit="m", ylabel=T("rmse_log_m"), title=T("s6_regime_depth_title"))

        depth_figs.append(P.plot_segment_breakdown(
            d_seg, os.path.join(OUTDIR, "s6_segment_breakdown_dzilums.png"),
            turn_labels=_depth_labels(), metric="iae", unit="m·s",
            title=T("s6_segment_depth_title")))
        P.plot_segment_breakdown(
            _no_f(d_seg),
            os.path.join(OUTDIR, "s6_segment_breakdown_dzilums_bez_fossen.png"),
            turn_labels=_depth_labels(), metric="iae", unit="m·s",
            title=T("s6_segment_depth_title"))

        # linthresh 0.01 m: the NMPC holds depth to centimetres, which the
        # heading ECDF's 0.5 linear threshold would collapse onto the axis.
        depth_figs.append(P.plot_error_ecdf(
            dict(d_err), os.path.join(OUTDIR, "s6_error_ecdf_dzilums.png"),
            unit=" m", xlabel=T("depth_err_abs"), linthresh=0.01,
            title=T("s6_ecdf_depth_title")))
        P.plot_error_ecdf(
            _no_f(d_err),
            os.path.join(OUTDIR, "s6_error_ecdf_dzilums_bez_fossen.png"),
            unit=" m", xlabel=T("depth_err_abs"), linthresh=0.01,
            title=T("s6_ecdf_depth_title"))

        depth_figs.append(P.plot_mission_overview(
            t, depth["series"], depth["ref"], d_err, SWITCH,
            os.path.join(OUTDIR, "s6_mission_overview_dzilums.png"),
            ylabel=T("depth_m"), err_ylabel=T("depth_error_m"),
            title=T("s6_overview_depth_title")))
        P.plot_mission_overview(
            t, _no_f(depth["series"]), depth["ref"], _no_f(d_err), SWITCH,
            os.path.join(OUTDIR, "s6_mission_overview_dzilums_bez_fossen.png"),
            ylabel=T("depth_m"), err_ylabel=T("depth_error_m"),
            title=T("s6_overview_depth_title"))

    # ---------------- reports ----------------
    R.write_csv(agg_rows,
                ["controller", "rmse_deg", "mae_deg", "iae_deg_s", "itae", "max_deg", "std_deg"],
                os.path.join(OUTDIR, "s6_summary_metrics.csv"))
    seg_csv_rows = []
    for name, rows in seg.items():
        for rrow in rows:
            seg_csv_rows.append({"controller": name, **rrow})
    R.write_csv(seg_csv_rows,
                ["controller", "start", "end", "iae", "mae", "rmse", "max_abs", "steady_state"],
                os.path.join(OUTDIR, "s6_segment_metrics.csv"))

    depth_md = ""
    if depth is not None:
        d_agg_rows = [{"controller": r["controller"], "rmse_m": r["rmse"],
                       "mae_m": r["mae"], "iae_m_s": r["iae"], "itae": r["itae"],
                       "max_m": r["max"], "std_m": r["std"]} for r in d_agg]
        R.write_csv(d_agg_rows,
                    ["controller", "rmse_m", "mae_m", "iae_m_s", "itae", "max_m", "std_m"],
                    os.path.join(OUTDIR, "s6_summary_metrics_dzilums.csv"))
        d_seg_rows = []
        for name, rows in d_seg.items():
            for rrow in rows:
                d_seg_rows.append({"controller": name, **rrow})
        R.write_csv(d_seg_rows,
                    ["controller", "start", "end", "iae", "mae", "rmse", "max_abs", "steady_state"],
                    os.path.join(OUTDIR, "s6_segment_metrics_dzilums.csv"))

        depth_agg_md = R.metrics_table_md(
            d_agg_rows,
            ["controller", "rmse_m", "mae_m", "iae_m_s", "max_m"],
            headers=[T("col_controller"), "RMSE [m]", "MAE [m]", "IAE [m·s]",
                     T("col_max_e_m")],
            nd=3)
        d_regime_rows = [
            {
                "controller": n,
                "aggregate": d_regimes[n][T("regime_aggregate")],
                "transient": d_regimes[n][T("regime_transient")],
                "settled":   d_regimes[n][T("regime_settled")],
            }
            for n in d_regimes
        ]
        depth_regime_md = R.metrics_table_md(
            d_regime_rows, ["controller", "aggregate", "transient", "settled"],
            headers=[T("col_controller"), T("col_aggregate_rmse_m"),
                     T("col_transient_rmse_m"), T("col_settled_rmse_m")], nd=4)
        depth_md = depth_agg_md + "\n\n" + depth_regime_md

    agg_md = R.metrics_table_md(
        agg_rows,
        ["controller", "rmse_deg", "mae_deg", "iae_deg_s", "max_deg"],
        headers=[T("col_controller"), "RMSE [°]", "MAE [°]", "IAE [°·s]", T("col_max_e")],
        nd=2)
    regime_rows = [
        {
            "controller": n,
            "aggregate": regimes[n][T("regime_aggregate")],
            "transient": regimes[n][T("regime_transient")],
            "settled":   regimes[n][T("regime_settled")],
        }
        for n in regimes
    ]
    split_md = R.metrics_table_md(
        regime_rows, ["controller", "aggregate", "transient", "settled"],
        headers=[T("col_controller"), T("col_aggregate_rmse"),
                 T("col_transient_rmse"), T("col_settled_rmse")], nd=3)

    # Worst NMPC excursions, quoted in the summary text below.
    nmpc_name = next(n for n in err_deg if "NMPC" in n)
    i_rev = int(np.argmax(np.abs(err_deg[nmpc_name])))
    i_dep_region = (t >= 255) & (t <= 335)
    i_dep = np.where(i_dep_region)[0][
        np.argmax(np.abs(err_deg[nmpc_name][i_dep_region]))]

    pid_name = "PID (tuned)"
    ss_pid  = np.mean([s["steady_state"] for s in seg[pid_name]])
    ss_nmpc = np.mean([s["steady_state"] for s in seg[nmpc_name]])
    agg_by_name = {r["controller"]: r for r in agg_rows}
    summary = (
        f"- **Aggregate heading RMSE:** "
        f"{pid_name} = {agg_by_name[pid_name]['rmse_deg']:.2f}°, "
        f"{nmpc_name} = {agg_by_name[nmpc_name]['rmse_deg']:.2f}° "
        f"— aggregate metric makes the second controller appear worse.\n"
        f"- **Steady-state holding error (mean across segments):** "
        f"{pid_name} = {ss_pid:.3f}°, "
        f"{nmpc_name} = {ss_nmpc:.3f}° "
        f"— NMPC is ~{ss_pid/max(ss_nmpc, 1e-9):.0f}× more precise in holding.\n"
        f"- **Root cause:** aggregate RMSE is dominated by two transient events — "
        f"reversal overshoot (~{abs(err_deg[nmpc_name][i_rev]):.0f}°, "
        f"t≈{t[i_rev]:.0f} s) and depth-coupling excursion "
        f"(~{abs(err_deg[nmpc_name][i_dep]):.0f}°, t≈{t[i_dep]:.0f} s).\n"
    )

    if depth is not None:
        d_by_name = {r["controller"]: r for r in d_agg}
        d_ss_pid  = np.mean([s["steady_state"] for s in d_seg[pid_name]])
        d_ss_nmpc = np.mean([s["steady_state"] for s in d_seg[nmpc_name]])
        summary += (
            f"- **Aggregate depth RMSE:** "
            f"{pid_name} = {d_by_name[pid_name]['rmse']:.3f} m, "
            f"{nmpc_name} = {d_by_name[nmpc_name]['rmse']:.3f} m; "
            f"holding error {d_ss_pid:.3f} m vs {d_ss_nmpc:.3f} m "
            f"— the same transient-vs-holding split as heading, in the depth "
            f"channel.\n"
        )

    sections = [
        ("Summary", summary),
        ("Aggregate metrics (heading)", agg_md),
        ("Heading error by regime", split_md),
    ]
    if depth_md:
        sections.append(("Depth tracking (aggregate and by regime)", depth_md))
    sections.append(
        ("Note", "All values from `s6_kursa_kludas_analize.csv` "
                 "(600 s, 50 Hz). Figures in `results/advanced/`; the depth "
                 "counterparts carry the `_dzilums` suffix."))

    R.write_markdown_report(
        os.path.join(OUTDIR, "s6_results.md"),
        "Scenario 6 in-depth analysis (heading and depth tracking)",
        sections,
    )

    print("Saved figures:")
    for f in (f1, f2, f3, f4, f5, f6, *depth_figs):
        print("  ", f)
    print("Saved data: s6_summary_metrics.csv, s6_segment_metrics.csv, s6_results.md")
    if depth is not None:
        print("            s6_summary_metrics_dzilums.csv, s6_segment_metrics_dzilums.csv")


if __name__ == "__main__":
    main()
