"""
thesis_analysis.py — Master's-level technical and statistical analysis
======================================================================

Produces a complete English technical report with root-cause analysis,
full performance metrics across operating regimes, and paired statistical
significance tests suitable for a master's thesis results chapter.

Data loading priority
---------------------
1. results/advanced/patch_compare_timeseries.csv
   Three-way comparison: PID (tuned), NMPC traj. (N=12), NMPC offset-free (N=12).
   Generated by:  python -m analysis.compare_nmpc_patch

2. results/s6_kursa_kludas_analize.csv  (fallback)
   Two-way comparison: PID (tuned), NMPC offset-free (N=12).
   Generated by:  python -m experiments.run_remus100_comparison

All outputs go to results/advanced/.

Run:
    python -m analysis.thesis_analysis
"""

from __future__ import annotations

import os
import sys
import math

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from analysis import metrics as M
from analysis import plotting as P
from config import T
from analysis import report as R

D2R = math.pi / 180.0
R2D = 180.0 / math.pi

RESULTS = os.path.join(ROOT, "results")
OUTDIR  = os.path.join(RESULTS, "advanced")

# Mission structure
WAYPOINTS = [(0, 0), (15, 0), (25, 90), (40, 90), (40, 200),
             (10, 200), (30, 330), (45, 45), (20, 0)]
SWITCH = [5, 60, 120, 180, 260, 340, 420, 500]
T_FINAL = 600.0
BOUNDS  = [0.0] + SWITCH + [T_FINAL]

WIN_DEPTH    = (255.0, 310.0)   # ascent transition + short settled tail
WIN_REVERSAL = (495.0, 560.0)   # reversal turn + short settled tail


# --------------------------------------------------------------------------- #
#  Data loading
# --------------------------------------------------------------------------- #
def load_data():
    """Load heading time-series.  Returns (t, ref_deg, controllers_dict).

    controllers_dict maps controller name -> {heading_cont_deg, err_deg}.
    """
    import pandas as pd

    three_way_path = os.path.join(OUTDIR, "patch_compare_timeseries.csv")
    two_way_path   = os.path.join(RESULTS, "s6_kursa_kludas_analize.csv")

    if os.path.exists(three_way_path):
        print(f"[thesis_analysis] Loading 3-way data from {three_way_path}")
        df = pd.read_csv(three_way_path)
        t = df["time_s"].values
        ref_deg = df["reference_cont_deg"].values
        ctrl_names = [
            "PID (tuned)",
            "NMPC traj. (N=12)",
            "NMPC offset-free (N=12)",
        ]
        controllers = {}
        for n in ctrl_names:
            cont_col = f"{n}_cont_deg"
            err_col  = f"{n}_err_deg"
            if cont_col in df.columns and err_col in df.columns:
                controllers[n] = {
                    "heading_cont_deg": df[cont_col].values,
                    "err_deg": df[err_col].values,
                }
        # The patch CSV has no Fossen builtin run; merge it from the
        # scenario-6 CSV (same seed/current realisation, same time grid)
        # so the deep-dive figures include the baseline.  Put it first so
        # it draws underneath the controllers of interest.
        if os.path.exists(two_way_path):
            df6 = pd.read_csv(two_way_path)
            pfx = "Fossen_PID/SMC"
            cont_col = f"{pfx}_heading_continuous_deg"
            err_col = f"{pfx}_heading_error_deg"
            if (cont_col in df6.columns and err_col in df6.columns
                    and len(df6) == len(df)):
                controllers = {
                    "Fossen PID/SMC": {
                        "heading_cont_deg": df6[cont_col].values,
                        "err_deg": df6[err_col].values,
                    },
                    **controllers,
                }
        return t, ref_deg, controllers

    if os.path.exists(two_way_path):
        print(f"[thesis_analysis] Loading 2-way data from {two_way_path}")
        df = pd.read_csv(two_way_path)
        t = df["time_s"].values
        ref_deg = df["reference_heading_continuous_deg"].values
        # Map stable internal names to CSV column prefixes
        col_map = {
            "Fossen PID/SMC":          "Fossen_PID/SMC",
            "PID (tuned)":             "PID_tuned",
            "PID (5 Hz)":              "PID_5_Hz",
            "NMPC offset-free (N=12)": "NMPC_offset-free_N12",
        }
        controllers = {}
        for name, pfx in col_map.items():
            cont_col = f"{pfx}_heading_continuous_deg"
            err_col  = f"{pfx}_heading_error_deg"
            if cont_col in df.columns and err_col in df.columns:
                controllers[name] = {
                    "heading_cont_deg": df[cont_col].values,
                    "err_deg": df[err_col].values,
                }
        return t, ref_deg, controllers

    raise FileNotFoundError(
        "No input CSV found.  Run one of:\n"
        "  python -m experiments.run_remus100_comparison\n"
        "  python -m analysis.compare_nmpc_patch")


# --------------------------------------------------------------------------- #
#  Performance metrics
# --------------------------------------------------------------------------- #
def compute_full_metrics(t, ref_deg, controllers):
    """Compute RMSE/MAE/IAE/ITAE/P95/P99/max across three regimes per controller.

    Returns nested dict: {name -> {'aggregate'|'transient'|'settled' -> {metric -> value}}}
    """
    ref_rad = ref_deg * D2R
    changing = [WAYPOINTS[i + 1][1] != WAYPOINTS[i][1] for i in range(len(SWITCH))]

    # Settled mask: last 40% of each segment
    settled_mask = np.zeros(len(t), bool)
    for a, b in zip(BOUNDS[:-1], BOUNDS[1:]):
        settled_mask |= (t >= a + 0.6 * (b - a)) & (t < b)

    out = {}
    for name, d in controllers.items():
        sig_rad = d["heading_cont_deg"] * D2R
        e_abs = np.abs(M.angle_error(sig_rad, ref_rad)) * R2D
        tm = M.tracking_metrics(t, sig_rad, ref_rad, angular=True)
        sp = M.split_transient_steady(t, sig_rad, ref_rad, SWITCH,
                                      angular=True, transient_window=35.0,
                                      only_changing=changing)
        e_full = M.angle_error(sig_rad, ref_rad) * R2D

        def _regime_metrics(mask):
            if not mask.any():
                return {k: float("nan") for k in
                        ("rmse", "mae", "iae", "itae", "p95", "p99", "max")}
            ea = np.abs(e_full[mask])
            return {
                "rmse": float(np.sqrt(np.mean(e_full[mask] ** 2))),
                "mae":  float(np.mean(ea)),
                "iae":  float(np.sum(ea) * float(np.median(np.diff(t)))),
                "itae": float(np.sum(t[mask] * ea) * float(np.median(np.diff(t)))),
                "p95":  float(np.percentile(ea, 95)),
                "p99":  float(np.percentile(ea, 99)),
                "max":  float(np.max(ea)),
            }

        # Transient mask: ±35 s after heading-changing waypoints
        trans_mask = np.zeros(len(t), bool)
        for i, ts in enumerate(SWITCH):
            if changing[i]:
                trans_mask |= (t >= ts) & (t < ts + 35.0)

        out[name] = {
            "aggregate": _regime_metrics(np.ones(len(t), bool)),
            "transient": _regime_metrics(trans_mask),
            "settled":   _regime_metrics(settled_mask),
        }
    return out


# --------------------------------------------------------------------------- #
#  Root cause analysis
# --------------------------------------------------------------------------- #
def root_cause_analysis(t, ref_deg, controllers, full_metrics):
    """Quantify the two NMPC failure modes.

    For each controller, compute the IAE contribution from each failure window
    and express it as a fraction of the total mission IAE.
    """
    dt = float(np.median(np.diff(t)))
    findings = {}
    for name, d in controllers.items():
        total_iae = full_metrics[name]["aggregate"]["iae"]
        entry = {}
        for label, window in [("depth_coupling", WIN_DEPTH),
                               ("reversal",       WIN_REVERSAL)]:
            mask = (t >= window[0]) & (t < window[1])
            if not mask.any():
                entry[label] = {"window_iae": 0.0, "pct": 0.0, "peak_deg": 0.0}
                continue
            w_iae = float(np.sum(np.abs(d["err_deg"][mask])) * dt)
            peak  = float(np.max(np.abs(d["err_deg"][mask])))
            entry[label] = {
                "window_iae": w_iae,
                "pct":        100.0 * w_iae / max(total_iae, 1e-9),
                "peak_deg":   peak,
            }
        findings[name] = entry
    return findings


# --------------------------------------------------------------------------- #
#  Statistical significance
# --------------------------------------------------------------------------- #
def statistical_tests(t, ref_deg, controllers):
    """Paired statistical tests across mission segments.

    Each of the 9 segments yields one per-controller MAE observation → valid
    paired comparison with n=9.  Computes:
      - paired t-test (p-value)
      - Wilcoxon signed-rank (p-value, if scipy present)
      - Cohen's d_z effect size
      - 95% confidence interval on the mean MAE difference
    """
    ref_rad = ref_deg * D2R
    # per-segment MAE for each controller
    seg_mae = {}
    for name, d in controllers.items():
        sig_rad = d["heading_cont_deg"] * D2R
        rows = M.segment_decompose(t, sig_rad, ref_rad, BOUNDS, angular=True)
        seg_mae[name] = [r["mae"] * R2D for r in rows]

    names = list(controllers)
    comparisons = []
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            cmp = M.paired_comparison(seg_mae[a], seg_mae[b], labels=(a, b))
            # 95% CI on mean difference (Student-t, df = n-1 = 8)
            d_arr = np.array(seg_mae[a]) - np.array(seg_mae[b])
            n_obs = len(d_arr)
            sem = np.std(d_arr, ddof=1) / max(np.sqrt(n_obs), 1e-9)
            try:
                from scipy import stats as _sps
                tcrit = float(_sps.t.ppf(0.975, df=n_obs - 1))
            except Exception:
                tcrit = 2.306  # t_{0.975, df=8} for n=9 segments
            cmp["ci_low_95"]  = cmp["mean_diff"] - tcrit * sem
            cmp["ci_high_95"] = cmp["mean_diff"] + tcrit * sem
            cmp["n_segments"] = n_obs
            comparisons.append(cmp)
    return comparisons


# --------------------------------------------------------------------------- #
#  Segment decomposition (for figures and tables)
# --------------------------------------------------------------------------- #
def compute_segments(t, ref_deg, controllers):
    ref_rad = ref_deg * D2R
    seg = {}
    for name, d in controllers.items():
        sig_rad = d["heading_cont_deg"] * D2R
        rows = M.segment_decompose(t, sig_rad, ref_rad, BOUNDS, angular=True,
                                   steady_frac=0.4)
        for r in rows:
            for k in ("iae", "mae", "rmse", "max_abs", "steady_state"):
                r[k] *= R2D
        seg[name] = rows
    return seg


# --------------------------------------------------------------------------- #
#  Turn labels for segments
# --------------------------------------------------------------------------- #
def _turn_labels():
    labels = []
    for k in range(len(BOUNDS) - 1):
        if k == 0:
            labels.append(T("seg_holding"))
            continue
        turn = (WAYPOINTS[k][1] - WAYPOINTS[k - 1][1] + 180.0) % 360.0 - 180.0
        labels.append(T("seg_holding") if abs(turn) < 1e-6
                      else f"{T('seg_turn')} {turn:+.0f}°")
    return labels


# --------------------------------------------------------------------------- #
#  Depth channel
# --------------------------------------------------------------------------- #
def load_depth_data():
    """Load the depth time-series for the same run as load_data().

    Returns ``(ref_depth_m, {name: {"depth_m", "err_m"}})``, or ``(None, None)``
    when the CSVs predate the depth columns.  Source preference mirrors
    load_data(): the 3-way patch CSV (which is the only place the original
    trajectory NMPC is run) with the Fossen baseline merged in from the
    scenario-6 CSV, falling back to the scenario-6 CSV alone.
    """
    import pandas as pd

    three_way_path = os.path.join(OUTDIR, "patch_compare_timeseries.csv")
    two_way_path   = os.path.join(RESULTS, "s6_kursa_kludas_analize.csv")

    def _fossen_depth(n_rows):
        if not os.path.exists(two_way_path):
            return None
        df6 = pd.read_csv(two_way_path)
        pfx = "Fossen_PID/SMC"
        if f"{pfx}_depth_m" not in df6.columns or len(df6) != n_rows:
            return None
        return {"depth_m": df6[f"{pfx}_depth_m"].values,
                "err_m": df6[f"{pfx}_depth_error_m"].values}

    if os.path.exists(three_way_path):
        df = pd.read_csv(three_way_path)
        if "reference_depth_m" in df.columns:
            ctrl = {}
            for n in ["PID (tuned)", "NMPC traj. (N=12)", "NMPC offset-free (N=12)"]:
                if f"{n}_depth_m" in df.columns:
                    ctrl[n] = {"depth_m": df[f"{n}_depth_m"].values,
                               "err_m": df[f"{n}_depth_err_m"].values}
            fossen = _fossen_depth(len(df))
            if fossen is not None:
                ctrl = {"Fossen PID/SMC": fossen, **ctrl}
            return df["reference_depth_m"].values, ctrl

    if os.path.exists(two_way_path):
        df = pd.read_csv(two_way_path)
        if "reference_depth_m" in df.columns:
            col_map = {
                "Fossen PID/SMC":          "Fossen_PID/SMC",
                "PID (tuned)":             "PID_tuned",
                "PID (5 Hz)":              "PID_5_Hz",
                "NMPC offset-free (N=12)": "NMPC_offset-free_N12",
            }
            ctrl = {name: {"depth_m": df[f"{pfx}_depth_m"].values,
                           "err_m": df[f"{pfx}_depth_error_m"].values}
                    for name, pfx in col_map.items()
                    if f"{pfx}_depth_m" in df.columns}
            return df["reference_depth_m"].values, ctrl

    return None, None


def _depth_labels():
    """Segment labels for the depth channel: the commanded depth change."""
    labels = []
    for k in range(len(BOUNDS) - 1):
        if k == 0:
            labels.append(T("seg_holding"))
            continue
        dz = WAYPOINTS[k][0] - WAYPOINTS[k - 1][0]
        labels.append(T("seg_holding") if abs(dz) < 1e-6 else f"{dz:+.0f} m")
    return labels


def compute_depth_metrics(t, ref_depth, dctrl):
    """Regime RMSE and per-segment decomposition for the depth channel.

    Transients are keyed to the waypoints that actually change DEPTH, so a
    pure heading turn is not scored as a depth manoeuvre.
    """
    changing = [WAYPOINTS[i + 1][0] != WAYPOINTS[i][0] for i in range(len(SWITCH))]
    settled_mask = np.zeros(len(t), bool)
    for a, b in zip(BOUNDS[:-1], BOUNDS[1:]):
        settled_mask |= (t >= a + 0.6 * (b - a)) & (t < b)
    trans_mask = np.zeros(len(t), bool)
    for i, ts in enumerate(SWITCH):
        if changing[i]:
            trans_mask |= (t >= ts) & (t < ts + 35.0)

    regimes, seg, rows_csv = {}, {}, []
    for name, d in dctrl.items():
        e = np.asarray(d["err_m"], float)

        def _rmse(mask):
            return float(np.sqrt(np.mean(e[mask] ** 2))) if mask.any() else float("nan")

        regimes[name] = {
            T("regime_aggregate"): _rmse(np.ones(len(t), bool)),
            T("regime_transient"): _rmse(trans_mask),
            T("regime_settled"):   _rmse(settled_mask),
        }
        seg[name] = M.segment_decompose(t, np.asarray(d["depth_m"], float),
                                        np.asarray(ref_depth, float), BOUNDS,
                                        angular=False, steady_frac=0.4)
        ae = np.abs(e)
        rows_csv.append({
            "controller": name,
            "rmse_m": regimes[name][T("regime_aggregate")],
            "transient_rmse_m": regimes[name][T("regime_transient")],
            "settled_rmse_m": regimes[name][T("regime_settled")],
            "mae_m": float(np.mean(ae)),
            "p95_m": float(np.percentile(ae, 95)),
            "max_m": float(np.max(ae)),
        })
    return regimes, seg, rows_csv


def generate_depth_figures(t, ref_depth, dctrl, regimes, seg, out_dir):
    """Depth twins of the thesis heading figures ("_dzilums" file names)."""
    FOSSEN = "Fossen PID/SMC"

    def _no_f(d):
        return {k: v for k, v in d.items() if k != FOSSEN}

    P.plot_regime_comparison(
        regimes, os.path.join(out_dir, "thesis_regime_comparison_dzilums.png"),
        unit="m", ylabel=T("rmse_log_m"), title=T("thesis_regime_depth_title"))
    P.plot_regime_comparison(
        _no_f(regimes),
        os.path.join(out_dir, "thesis_regime_comparison_dzilums_bez_fossen.png"),
        unit="m", ylabel=T("rmse_log_m"), title=T("thesis_regime_depth_title"))

    err_data = {n: d["err_m"] for n, d in dctrl.items()}
    # linthresh 0.01 m: the heading default of 0.5 would flatten the NMPC curves.
    P.plot_error_ecdf(
        err_data, os.path.join(out_dir, "thesis_error_ecdf_dzilums.png"),
        unit=" m", xlabel=T("depth_err_abs"), linthresh=0.01,
        title=T("thesis_ecdf_depth_title"))
    P.plot_error_ecdf(
        _no_f(err_data),
        os.path.join(out_dir, "thesis_error_ecdf_dzilums_bez_fossen.png"),
        unit=" m", xlabel=T("depth_err_abs"), linthresh=0.01,
        title=T("thesis_ecdf_depth_title"))

    P.plot_segment_breakdown(
        seg, os.path.join(out_dir, "thesis_segment_breakdown_dzilums.png"),
        turn_labels=_depth_labels(), metric="iae", unit="m·s",
        title=T("thesis_segment_depth_title"))
    P.plot_segment_breakdown(
        _no_f(seg),
        os.path.join(out_dir, "thesis_segment_breakdown_dzilums_bez_fossen.png"),
        turn_labels=_depth_labels(), metric="iae", unit="m·s",
        title=T("thesis_segment_depth_title"))

    depth_data = {n: d["depth_m"] for n, d in dctrl.items()}
    for win, base, ttl in (
        (WIN_REVERSAL, "thesis_zoom_reversal_dzilums", T("thesis_zoom_rev_depth_title")),
        (WIN_DEPTH, "thesis_zoom_depthcoupling_dzilums", T("thesis_zoom_depth_dz_title")),
    ):
        P.plot_spike_zoom(t, _no_f(depth_data), ref_depth, win,
                          os.path.join(out_dir, f"{base}.png"), title=ttl,
                          unit="m", ylabel=T("depth_m"))
        P.plot_spike_zoom(t, depth_data, ref_depth, win,
                          os.path.join(out_dir, f"{base}_ar_fossen.png"), title=ttl,
                          unit="m", ylabel=T("depth_m"))

    P.plot_mission_overview(
        t, depth_data, ref_depth, err_data, SWITCH,
        os.path.join(out_dir, "thesis_mission_overview_dzilums.png"),
        ylabel=T("depth_m"), err_ylabel=T("depth_error_m"),
        title=T("thesis_overview_depth_title"))
    P.plot_mission_overview(
        t, _no_f(depth_data), ref_depth, _no_f(err_data), SWITCH,
        os.path.join(out_dir, "thesis_mission_overview_dzilums_bez_fossen.png"),
        ylabel=T("depth_m"), err_ylabel=T("depth_error_m"),
        title=T("thesis_overview_depth_title"))


# --------------------------------------------------------------------------- #
#  Figures
# --------------------------------------------------------------------------- #
def generate_figures(t, ref_deg, controllers, full_metrics, seg_data, out_dir):
    """Generate all thesis-level figures in English.

    Every figure is written twice: the default name, and a variant with the
    Fossen baseline toggled the other way ("_bez_fossen" = without,
    "_ar_fossen" = with).  Defaults: with Fossen everywhere except the zooms,
    where its tens-of-degrees error would flatten the other curves.
    """
    FOSSEN = "Fossen PID/SMC"

    def _no_f(d):
        return {k: v for k, v in d.items() if k != FOSSEN}

    # 1. Regime comparison
    regime_data = {}
    for name, fm in full_metrics.items():
        regime_data[name] = {
            T("regime_aggregate"): fm["aggregate"]["rmse"],
            T("regime_transient"): fm["transient"]["rmse"],
            T("regime_settled"):   fm["settled"]["rmse"],
        }
    P.plot_regime_comparison(
        regime_data,
        os.path.join(out_dir, "thesis_regime_comparison.png"),
        title=T("thesis_regime_title"))
    P.plot_regime_comparison(
        _no_f(regime_data),
        os.path.join(out_dir, "thesis_regime_comparison_bez_fossen.png"),
        title=T("thesis_regime_title"))

    # 2. Error ECDF
    err_data = {n: d["err_deg"] for n, d in controllers.items()}
    P.plot_error_ecdf(
        err_data,
        os.path.join(out_dir, "thesis_error_ecdf.png"),
        title=T("thesis_ecdf_title"))
    P.plot_error_ecdf(
        _no_f(err_data),
        os.path.join(out_dir, "thesis_error_ecdf_bez_fossen.png"),
        title=T("thesis_ecdf_title"))

    # 3. Segment breakdown
    P.plot_segment_breakdown(
        seg_data,
        os.path.join(out_dir, "thesis_segment_breakdown.png"),
        turn_labels=_turn_labels(), metric="iae", unit="°·s",
        title=T("thesis_segment_title"))
    P.plot_segment_breakdown(
        _no_f(seg_data),
        os.path.join(out_dir, "thesis_segment_breakdown_bez_fossen.png"),
        turn_labels=_turn_labels(), metric="iae", unit="°·s",
        title=T("thesis_segment_title"))

    # 4 & 5. Zooms (default without Fossen; "_ar_fossen" variant with it)
    heading_data = {n: d["heading_cont_deg"] for n, d in controllers.items()}
    for win, base in ((WIN_REVERSAL, "thesis_zoom_reversal"),
                      (WIN_DEPTH, "thesis_zoom_depthcoupling")):
        ttl = T("thesis_zoom_rev_title") if base.endswith("reversal") \
            else T("thesis_zoom_depth_title")
        P.plot_spike_zoom(
            t, _no_f(heading_data), ref_deg, win,
            os.path.join(out_dir, f"{base}.png"), title=ttl)
        P.plot_spike_zoom(
            t, heading_data, ref_deg, win,
            os.path.join(out_dir, f"{base}_ar_fossen.png"), title=ttl)

    # 6. Mission overview
    P.plot_mission_overview(
        t,
        heading_data,
        ref_deg,
        err_data,
        SWITCH,
        os.path.join(out_dir, "thesis_mission_overview.png"),
        title=T("thesis_overview_title"))
    P.plot_mission_overview(
        t,
        _no_f(heading_data),
        ref_deg,
        _no_f(err_data),
        SWITCH,
        os.path.join(out_dir, "thesis_mission_overview_bez_fossen.png"),
        title=T("thesis_overview_title"))


# --------------------------------------------------------------------------- #
#  CSV outputs
# --------------------------------------------------------------------------- #
def write_metric_csvs(full_metrics, seg_data, stat_tests, out_dir):
    # Full metric table (all regimes)
    rows = []
    for name, fm in full_metrics.items():
        for regime, mets in fm.items():
            rows.append({"controller": name, "regime": regime, **mets})
    R.write_csv(rows,
                ["controller", "regime", "rmse", "mae", "iae", "itae", "p95", "p99", "max"],
                os.path.join(out_dir, "thesis_full_metrics.csv"))

    # Statistical tests
    stat_rows = []
    for cmp in stat_tests:
        stat_rows.append({
            "comparison":    f"{cmp['label_a']}  vs  {cmp['label_b']}",
            "n_segments":    cmp.get("n_segments", ""),
            "mean_diff_deg": f"{cmp['mean_diff']:.4f}",
            "ci_low_95":     f"{cmp.get('ci_low_95', float('nan')):.4f}",
            "ci_high_95":    f"{cmp.get('ci_high_95', float('nan')):.4f}",
            "paired_t_p":    f"{cmp.get('paired_t_p', float('nan')):.4f}",
            "wilcoxon_p":    f"{cmp.get('wilcoxon_p', float('nan')):.4f}",
            "cohen_dz":      f"{cmp.get('cohen_dz', float('nan')):.3f}",
        })
    R.write_csv(stat_rows,
                ["comparison", "n_segments", "mean_diff_deg", "ci_low_95",
                 "ci_high_95", "paired_t_p", "wilcoxon_p", "cohen_dz"],
                os.path.join(out_dir, "thesis_stat_tests.csv"))


# --------------------------------------------------------------------------- #
#  Markdown report
# --------------------------------------------------------------------------- #
def generate_report(t, ref_deg, controllers, full_metrics, root_cause, stat_tests,
                    seg_data, out_dir):
    """Write a comprehensive master's-level English Markdown report."""

    names = list(controllers)
    # startswith, not substring: "Fossen PID/SMC" must not match here
    pid_name  = next((n for n in names if n.startswith("PID")), names[0])
    nmpc_names = [n for n in names if "NMPC" in n]
    orig_name  = next((n for n in nmpc_names if "traj" in n), None)
    patch_name = next((n for n in nmpc_names if "offset" in n),
                      nmpc_names[-1] if nmpc_names else None)

    # ---- §1 Executive summary ----
    if patch_name:
        agg_pid   = full_metrics[pid_name]["aggregate"]["rmse"]
        agg_patch = full_metrics[patch_name]["aggregate"]["rmse"]
        ss_pid    = full_metrics[pid_name]["settled"]["rmse"]
        ss_patch  = full_metrics[patch_name]["settled"]["rmse"]
        ratio_ss  = ss_pid / max(ss_patch, 1e-9)
        exec_summary = (
            f"Scenario 6 (600 s, 8-waypoint complex mission, current 0.6 m/s @ 150°) "
            f"was used to compare a tuned cascaded PID and trajectory NMPC controllers "
            f"on the REMUS 100 AUV.  The aggregate heading RMSE of the patched "
            f"NMPC ({agg_patch:.2f}°) is {'lower' if agg_patch < agg_pid else 'higher'} "
            f"than the PID ({agg_pid:.2f}°), but this aggregate figure is dominated by "
            f"two specific transient failure modes.  In settled holding, "
            f"NMPC is {ratio_ss:.0f}× more accurate than PID "
            f"({ss_patch:.3f}° vs {ss_pid:.3f}° RMSE).  "
            f"The patched NMPC (offset-free disturbance observer) "
            f"directly addresses both failure modes identified in this analysis."
        )
    else:
        exec_summary = "See §3 for full metrics."

    # ---- §2 Root cause analysis ----
    rc_pid   = root_cause.get(pid_name, {})
    rc_orig  = root_cause.get(orig_name, {}) if orig_name else {}
    rc_patch = root_cause.get(patch_name, {}) if patch_name else {}

    def _rc_table(findings, name):
        if not findings:
            return ""
        depth = findings.get("depth_coupling", {})
        rev   = findings.get("reversal", {})
        return (
            f"| Window | Peak error | Window IAE | % of total IAE |\n"
            f"|--------|-----------|------------|----------------|\n"
            f"| Depth coupling (260–340 s) | {depth.get('peak_deg', 0):.1f}° "
            f"| {depth.get('window_iae', 0):.1f} °·s | {depth.get('pct', 0):.1f}% |\n"
            f"| Reversal (490–570 s) | {rev.get('peak_deg', 0):.1f}° "
            f"| {rev.get('window_iae', 0):.1f} °·s | {rev.get('pct', 0):.1f}% |\n"
        )

    root_cause_text = f"""> **Historical note.** The two failure modes below were identified on earlier
> development runs (original N=20 controller, and the patched controller before
> the surge-channel model fix).  They document *why* the patched controller and
> the corrected CasADi predictor exist.  In the current results (tables below
> and §3) both windows show only small residual errors: the surge predictor now
> includes the advance-ratio thrust loss, state limits are soft constraints,
> and the disturbance observer has a decay term.

### Failure Mode 1 — Reversal Overshoot (490–570 s)

**Physical cause — disturbance observer with no decay:**
The offset-free observer estimates a yaw angular-acceleration disturbance
`d_r` [rad/s²] by accumulating the one-step yaw-rate prediction error:

    d_r[k] = (1−α)·d_r[k−1] + α·(d_r[k−1] + L·ν_r[k] / dt)

Without a decay term, `d_r` acts as a pure integrator that holds its value
indefinitely once the disturbance ends.  During the depth-coupling window
(260–340 s), the unmodelled pitch→yaw coupling drives `d_r` to its negative
saturation limit (large counter-clockwise angular-acceleration estimate).
After the ascent completes, `ν_r → 0` (the NMPC compensates in closed-loop),
so `d_r` never decays — it remains locked at the stale saturated value for
all subsequent segments.

At t = 500 s, the mission commands a −45° (counter-clockwise) heading turn
from 45° to 0° while simultaneously initiating a second depth change (45 m →
20 m).  The stale `d_r` (large CCW) causes the NMPC predictor to expect rapid
counter-clockwise yaw acceleration even with no rudder.  To prevent exceeding
the yaw-rate constraint, IPOPT responds by commanding strong clockwise (positive)
rudder — exactly the opposite of what the turn requires.  The AUV heads clock-
wise instead of counter-clockwise, producing the observed 74° overshoot.

**Secondary cause — excessive depth rate creating modelling mismatch:**
The default `z_rate_max = 2.0 m/s` allows depth transitions at rates that
require pitch angles up to asin(2.0/2.5) ≈ 53°, far exceeding the NMPC
predictor's `θ_max = 25°` pitch constraint.  This large predictor–plant
mismatch amplifies the coupling disturbance during steep dives, driving `d_r`
to saturation faster and keeping it there longer.

**Fixes applied:**

1. **Observer leak** (`obs_leak = 0.005` per step): applies a per-step
   multiplicative decay to `d_r` so stale estimates decay with time constant
   τ = dt / obs_leak ≈ 0.2 / 0.005 = 40 steps ≈ 8 s.  After 160 s without
   active coupling the estimate decays to < 2% of its peak value.

2. **Depth-rate cap** (`z_rate_max = 1.0 m/s`): limits depth transitions to
   rates requiring pitch ≤ asin(1.0/2.5) ≈ 24°, consistent with the NMPC
   predictor's pitch constraint and therefore eliminating the modelling
   mismatch that saturated the observer.

3. **SSA warm-start override**: at each MPC call the initial guess for ψ is
   overridden with a linear interpolation in the SSA-shortest direction to the
   horizon-end reference heading, so IPOPT starts in the correct turn direction
   regardless of the previous warm-start state.

### Failure Mode 2 — Depth-Coupling Excursion (260–340 s)

**Physical cause:** The CasADi reduced-order predictor sets pitch→yaw coupling
to zero.  During ascent, the real Fossen hull generates a yaw moment through
pitch-yaw inertial coupling:

    r_dot_true = (N_rudder − d_yaw·r) / I₆₆ + (N_vr·v·r + N_wp·w·p + ...)/ I₆₆

The terms in parentheses are absent from the predictor (δ_r ≠ 0 throughout
the dive).  With `z_rate_max = 2.0 m/s` the required pitch angle (≈ 53°)
far exceeds `θ_max = 25°`, so the coupling moment is also much larger than
the observer can track (which only estimates a single scalar `d_r`).

**Fixes applied (same two fixes as above):**
The depth-rate cap limits the pitch angle to ≤ 24°, dramatically reducing the
coupling moment; the observer with leakage quickly tracks the remaining smaller
disturbance and the heading excursion is substantially reduced.

### Quantification

**{pid_name}:**
{_rc_table(rc_pid, pid_name)}
"""
    if orig_name:
        root_cause_text += f"**{orig_name} (original, reference):**\n{_rc_table(rc_orig, orig_name)}\n"
    if patch_name and patch_name != orig_name:
        root_cause_text += f"**{patch_name} (patched):**\n{_rc_table(rc_patch, patch_name)}\n"

    # ---- §3 full metric table ----
    metric_rows = []
    for name, fm in full_metrics.items():
        for regime, mets in fm.items():
            metric_rows.append({
                "Controller": name,
                "Regime":     regime,
                "RMSE [°]":   f"{mets['rmse']:.3f}",
                "MAE [°]":    f"{mets['mae']:.3f}",
                "IAE [°·s]":  f"{mets['iae']:.1f}",
                "P95 [°]":    f"{mets['p95']:.2f}",
                "P99 [°]":    f"{mets['p99']:.2f}",
                "Max |e| [°]":f"{mets['max']:.2f}",
            })
    metric_cols = ["Controller", "Regime", "RMSE [°]", "MAE [°]",
                   "IAE [°·s]", "P95 [°]", "P99 [°]", "Max |e| [°]"]
    full_metric_md = R.metrics_table_md(metric_rows, metric_cols, nd=3)

    # ---- §4 statistical significance ----
    def _p_str(p):
        if not isinstance(p, (float, int)) or math.isnan(float(p)):
            return "N/A"
        p = float(p)
        if p < 0.001:
            return "< 0.001"
        return f"{p:.4f}"

    def _eff(d):
        if not isinstance(d, (float, int)) or math.isnan(float(d)):
            return "N/A"
        d = abs(float(d))
        if d >= 0.8:
            return f"{d:.3f} (large)"
        if d >= 0.5:
            return f"{d:.3f} (medium)"
        return f"{d:.3f} (small)"

    stat_lines = []
    for cmp in stat_tests:
        stat_lines.append(
            f"#### {cmp['label_a']}  vs  {cmp['label_b']}\n\n"
            f"| Statistic | Value |\n"
            f"|-----------|-------|\n"
            f"| n (mission segments) | {cmp.get('n_segments', '?')} |\n"
            f"| Mean difference [°] | {cmp['mean_diff']:.3f} |\n"
            f"| 95% CI [°] | [{cmp.get('ci_low_95', float('nan')):.3f}, "
            f"{cmp.get('ci_high_95', float('nan')):.3f}] |\n"
            f"| Paired t-test p-value | {_p_str(cmp.get('paired_t_p'))} |\n"
            f"| Wilcoxon p-value | {_p_str(cmp.get('wilcoxon_p'))} |\n"
            f"| Cohen's d_z | {_eff(cmp.get('cohen_dz'))} |\n"
        )
    if not stat_lines:
        stat_lines = ["Insufficient data for statistical tests (need ≥ 2 controllers)."]
    stat_text = "\n".join(stat_lines)

    # ---- §5 segment breakdown ----
    seg_rows = []
    turn_labels = _turn_labels()
    for i, (a, b) in enumerate(zip(BOUNDS[:-1], BOUNDS[1:])):
        row = {"Segment": f"{int(a)}–{int(b)} s",
               "Manoeuvre": turn_labels[i] if i < len(turn_labels) else ""}
        for name, rows in seg_data.items():
            if i < len(rows):
                row[f"{name} IAE [°·s]"] = f"{rows[i]['iae']:.1f}"
                row[f"{name} SS [°]"]    = f"{rows[i]['steady_state']:.3f}"
        seg_rows.append(row)
    seg_cols = ["Segment", "Manoeuvre"]
    for name in seg_data:
        seg_cols += [f"{name} IAE [°·s]", f"{name} SS [°]"]
    seg_md = R.metrics_table_md(seg_rows, seg_cols, nd=3)

    # ---- §6 failure window dissection ----
    def _win_table(window_label, window, root_cause_data):
        lines = [f"| Controller | Peak error [°] | Window IAE [°·s] | % of total IAE |",
                 f"|------------|----------------|-----------------|----------------|"]
        for name in names:
            w = root_cause_data.get(name, {}).get(window_label, {})
            lines.append(f"| {name} | {w.get('peak_deg', 0):.1f} "
                         f"| {w.get('window_iae', 0):.1f} | {w.get('pct', 0):.1f}% |")
        return "\n".join(lines)

    failure_text = (
        f"### Depth-coupling excursion ({WIN_DEPTH[0]:.0f}–{WIN_DEPTH[1]:.0f} s)\n\n"
        "Pure ascent (40 m → 10 m) at constant heading 200°.  Heading drift is caused "
        "entirely by the unmodelled pitch→yaw coupling in the reduced predictor.\n\n"
        + _win_table("depth_coupling", WIN_DEPTH, root_cause) + "\n\n"
        f"### Reversal ({WIN_REVERSAL[0]:.0f}–{WIN_REVERSAL[1]:.0f} s)\n\n"
        "Sharp heading reversal (330°→45°→0°) combined with a 45 m → 20 m climb.\n\n"
        + _win_table("reversal", WIN_REVERSAL, root_cause)
    )

    # ---- §7 conclusions ----
    if patch_name:
        patch_agg_rmse = full_metrics[patch_name]["aggregate"]["rmse"]
        patch_ss_rmse  = full_metrics[patch_name]["settled"]["rmse"]
        orig_agg_rmse  = full_metrics.get(orig_name, {}).get("aggregate", {}).get("rmse", float("nan")) if orig_name else float("nan")
        pid_agg   = full_metrics[pid_name]["aggregate"]["rmse"]
        pid_ss    = full_metrics[pid_name]["settled"]["rmse"]
        conclusions = (
            f"1. **Root cause of the 74° reversal overshoot was a missing decay term in "
            f"the disturbance observer**, not the prediction horizon.  The observer's "
            f"integral action accumulated a large counter-clockwise disturbance estimate "
            f"during the first depth change (260–340 s) and held it indefinitely — "
            f"through 160 s and two subsequent heading turns — until it directly sabotaged "
            f"the counter-clockwise turn at t = 500 s.\n\n"
            f"2. **Two targeted fixes eliminate both failure modes:**\n"
            f"   - Observer leak (τ ≈ 8 s) prevents stale disturbance estimates from "
            f"persisting across unrelated mission segments.\n"
            f"   - Depth-rate cap (`z_rate_max = 1.0 m/s`) keeps pitch within the NMPC "
            f"predictor's constraint, eliminating the modelling mismatch that had saturated "
            f"the observer and amplified the coupling.\n\n"
            f"3. **Regime decomposition** is essential for fair comparison: aggregate RMSE "
            f"is dominated by brief transient events.  In steady-state heading holding, "
            f"the NMPC is significantly more accurate than PID "
            f"({patch_ss_rmse:.3f}° vs {pid_ss:.3f}° RMSE).\n\n"
            f"4. **Patched NMPC aggregate RMSE = {patch_agg_rmse:.2f}°**, "
            f"settled RMSE = {patch_ss_rmse:.3f}°.  "
            f"PID aggregate RMSE = {pid_agg:.2f}°.  "
            + (f"Original NMPC aggregate RMSE = {orig_agg_rmse:.2f}°. "
               if not math.isnan(orig_agg_rmse) else "")
            + f"\n\n"
            f"5. **Limitations:** All results come from a single deterministic simulation "
            f"run.  A Monte-Carlo robustness study (see `analysis/run_advanced_experiments.py`) "
            f"is required to make statistical claims about the full disturbance distribution."
        )
    else:
        conclusions = (
            "1. Regime decomposition reveals that aggregate RMSE is dominated by transient "
            "events; settled holding accuracy tells a different story.\n"
            "2. See §2 for root causes.\n"
        )

    # ---- write report ----
    R.write_markdown_report(
        os.path.join(out_dir, "thesis_report.md"),
        "AUV NMPC Thesis Analysis — Scenario 6 Comprehensive Report",
        [
            ("§1 Executive Summary", exec_summary),
            ("§2 Root Cause Analysis", root_cause_text),
            ("§3 Full Performance Metrics", full_metric_md),
            ("§4 Statistical Significance", stat_text),
            ("§5 Per-Segment Breakdown", seg_md),
            ("§6 Failure Window Dissection", failure_text),
            ("§7 Conclusions", conclusions),
            ("Data sources",
             f"- CSV: `results/advanced/patch_compare_timeseries.csv` or "
             f"`results/s6_kursa_kludas_analize.csv`\n"
             f"- Figures: `results/advanced/thesis_*.png`\n"
             f"- This report: `results/advanced/thesis_report.md`"),
        ],
    )


# --------------------------------------------------------------------------- #
#  Solver timing analysis
# --------------------------------------------------------------------------- #
DT_MPC = 0.2          # NMPC update interval [s] — real-time deadline

def load_solve_times():
    """Load controller solve times from the Scenario 6 CSV.

    Returns (mission_time_s, nmpc_ms, pid50_ms, pid5_ms).
    Any missing column returns None for that array.
    """
    import pandas as pd
    path = os.path.join(RESULTS, "nmpc_solve_times_s6.csv")
    if not os.path.exists(path):
        return None, None, None, None
    df = pd.read_csv(path)

    def _col(name):
        if name not in df.columns:
            return None
        vals = pd.to_numeric(df[name], errors="coerce").values
        return vals[~np.isnan(vals)] if np.any(~np.isnan(vals)) else None

    t_ms   = df["mission_time_s"].values
    nmpc   = _col("nmpc_solve_time_ms")
    pid50  = _col("pid50_solve_time_ms")
    pid5   = _col("pid5_solve_time_ms")
    # Legacy column name (older CSV)
    if pid50 is None and pid5 is None:
        pid50 = _col("pid_solve_time_ms")
    return t_ms, nmpc, pid50, pid5


def generate_timing_figures(out_dir: str):
    """Generate two solver-timing figures and a summary CSV comparing NMPC vs PID.

    thesis_solver_timeline.png  — per-call solve time across the mission (log scale)
    thesis_solver_distribution.png — overlaid histograms + ECDF, deadline marked
    thesis_solver_stats.csv — summary statistics for both controllers
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker

    t_s, nmpc_ms, pid50_ms, pid5_ms = load_solve_times()
    if t_s is None:
        print("[thesis_analysis] Solver timing CSV not found — skipping timing figures.")
        return

    deadline_ms = DT_MPC * 1000.0   # 200 ms

    def _stats(arr):
        if arr is None:
            return {}
        arr = np.asarray(arr, float)
        arr = arr[~np.isnan(arr)]
        if len(arr) == 0:
            return {}
        return dict(
            n=len(arr), mean=float(np.mean(arr)), med=float(np.median(arr)),
            std=float(np.std(arr)),
            p90=float(np.percentile(arr, 90)),
            p95=float(np.percentile(arr, 95)),
            p99=float(np.percentile(arr, 99)),
            max=float(np.max(arr)),
            pct_ok=float(np.mean(arr < deadline_ms) * 100.0),
        )

    ns  = _stats(nmpc_ms)
    p50 = _stats(pid50_ms)
    p5  = _stats(pid5_ms)

    # Write CSV
    import csv as _csv
    csv_path = os.path.join(out_dir, "thesis_solver_stats.csv")
    with open(csv_path, "w", newline="") as f:
        w = _csv.writer(f)
        w.writerow(["metric", "NMPC_offset-free_N12", "PID_50Hz", "PID_5Hz"])
        for key in ("n", "mean", "med", "std", "p90", "p95", "p99", "max", "pct_ok"):
            nv  = f"{ns[key]:.4f}"  if ns  else ""
            pv50 = f"{p50[key]:.4f}" if p50 else ""
            pv5  = f"{p5[key]:.4f}"  if p5  else ""
            w.writerow([key, nv, pv50, pv5])
        w.writerow(["deadline_ms", f"{deadline_ms:.0f}", f"{deadline_ms:.0f}", f"{deadline_ms:.0f}"])

    SEGMENT_LABELS = [
        T("seg_holding"), T("seg_holding"), "+90°", "+110°", "+130°",
        T("seg_ascent"), "+115°", "+75°", "−45°",
    ]
    bounds_s = [0.0] + SWITCH + [T_FINAL]

    COL_NMPC = "#2c7bb6"
    COL_P50  = "#1a9641"
    COL_P5   = "#e67e22"

    # ---- Figure 1: timeline (log-scale y) ----
    fig, axes = plt.subplots(2, 1, figsize=(14, 8),
                             gridspec_kw={"height_ratios": [4, 1]})
    fig.suptitle(T("timing_timeline_title"), fontsize=12, fontweight="bold")

    ax = axes[0]
    if nmpc_ms is not None:
        ax.semilogy(t_s[:len(nmpc_ms)], nmpc_ms, color=COL_NMPC, lw=0.7, alpha=0.5,
                    label=f"NMPC (5 Hz),  {T('ecdf_mean_label')}={ns['mean']:.1f} ms")
        if len(nmpc_ms) >= 20:
            roll_n = np.convolve(nmpc_ms, np.ones(20) / 20, mode="same")
            ax.semilogy(t_s[:len(nmpc_ms)], roll_n, color=COL_NMPC, lw=1.8, alpha=0.9,
                        label=f"NMPC {T('rolling_mean_label')}")
    if pid50_ms is not None:
        ax.semilogy(t_s[:len(pid50_ms)], pid50_ms, color=COL_P50, lw=0.7, alpha=0.5,
                    label=f"PID 50 Hz,  {T('ecdf_mean_label')}={p50['mean']:.4f} ms")
        if len(pid50_ms) >= 20:
            roll_p = np.convolve(pid50_ms, np.ones(20) / 20, mode="same")
            ax.semilogy(t_s[:len(pid50_ms)], roll_p, color=COL_P50, lw=1.8,
                        label=f"PID 50 Hz {T('rolling_mean_label')}")
    if pid5_ms is not None:
        ax.semilogy(t_s[:len(pid5_ms)], pid5_ms, color=COL_P5, lw=0.7, alpha=0.5,
                    label=f"PID 5 Hz,   {T('ecdf_mean_label')}={p5['mean']:.4f} ms")
        if len(pid5_ms) >= 20:
            roll_p5 = np.convolve(pid5_ms, np.ones(20) / 20, mode="same")
            ax.semilogy(t_s[:len(pid5_ms)], roll_p5, color=COL_P5, lw=1.8,
                        label=f"PID 5 Hz {T('rolling_mean_label')}")

    ax.axhline(deadline_ms, color="k", ls="--", lw=1.3,
               label=T("deadline_label").format(ms=deadline_ms))

    # shade segments
    for i, (a, b) in enumerate(zip(bounds_s[:-1], bounds_s[1:])):
        if i % 2 == 1:
            ax.axvspan(a, b, alpha=0.06, color="gray")
        ax.text((a + b) / 2, ax.get_ylim()[0] if ax.get_ylim()[0] > 0 else 1e-4,
                SEGMENT_LABELS[i] if i < len(SEGMENT_LABELS) else "",
                ha="center", va="bottom", fontsize=6.5, color="#555555",
                transform=ax.get_xaxis_transform())

    ax.set_ylabel(T("timing_time_ylab"))
    ax.set_xlim(0, T_FINAL)
    ax.legend(fontsize=8.5, loc="upper right")
    ax.grid(True, which="both", alpha=0.25)

    # lower strip: NMPC deadline violations
    ax2 = axes[1]
    if nmpc_ms is not None:
        over = (nmpc_ms >= deadline_ms).astype(float)
        ax2.fill_between(t_s, over, step="post", color="#d7191c", alpha=0.8)
    ax2.set_ylim(-0.1, 1.5)
    ax2.set_yticks([0, 1])
    ax2.set_yticklabels([T("timing_tick_ok"), T("timing_tick_over")], fontsize=8)
    ax2.set_xlabel(T("timing_time_xlab"))
    ax2.set_xlim(0, T_FINAL)
    ax2.grid(True, alpha=0.2)

    fig.tight_layout()
    p1 = os.path.join(out_dir, "thesis_solver_timeline.png")
    fig.savefig(p1, dpi=150, bbox_inches="tight")
    plt.close(fig)

    # ---- Figure 2: distribution comparison ----
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle(T("timing_main_title"), fontsize=13, fontweight="bold")

    controllers = [
        (nmpc_ms,  COL_NMPC, "NMPC (5 Hz)",   ns),
        (pid50_ms, COL_P50,  "PID (50 Hz)",    p50),
        (pid5_ms,  COL_P5,   "PID (5 Hz)",     p5),
    ]

    # Histogram — log x so PID (~0.025 ms) and NMPC (~25 ms) both visible
    ax = axes[0]
    all_vals = []
    for arr, col, lbl, st in controllers:
        if arr is None or not st:
            continue
        a = np.asarray(arr, float)
        a = a[~np.isnan(a) & (a > 0)]
        all_vals.extend(a.tolist())

    if all_vals:
        lo = np.log10(max(min(all_vals), 1e-4))
        hi = np.log10(max(all_vals) * 1.5)
        bins = np.logspace(lo, hi, 60)
        for arr, col, lbl, st in controllers:
            if arr is None or not st:
                continue
            a = np.asarray(arr, float)
            a = a[~np.isnan(a) & (a > 0)]
            ax.hist(a, bins=bins, color=col, edgecolor="white", lw=0.3,
                    alpha=0.72, label=f"{lbl}  (n={st['n']:,})")
        ax.set_xscale("log")

    ax.axvline(deadline_ms, color="k", ls="--", lw=1.5,
               label=T("deadline_label").format(ms=deadline_ms))
    ax.set_xlabel(T("timing_xlab"))
    ax.set_ylabel(T("timing_ylab_hist"))
    ax.set_title(T("timing_hist_title"))
    ax.grid(True, which="both", alpha=0.3)
    # Legend collected later for shared figure legend

    # ECDF — log x
    ax = axes[1]
    for arr, col, lbl, st in controllers:
        if arr is None or not st:
            continue
        a = np.asarray(arr, float)
        a = a[~np.isnan(a) & (a > 0)]
        s = np.sort(a)
        cdf = np.arange(1, len(s) + 1) / len(s) * 100
        ax.semilogx(s, cdf, color=col, lw=2.0,
                    label=f"{lbl}  {T('ecdf_mean_label')}={st['mean']:.4f} ms  P99={st['p99']:.4f} ms")
        # Mark only P99 with a single dotted line — no text labels to avoid clutter
        ax.axvline(st["p99"], color=col, ls=":", lw=1.2, alpha=0.7)

    ax.axvline(deadline_ms, color="k", ls="--", lw=1.5,
               label=T("deadline_label").format(ms=deadline_ms))
    ax.set_xlabel(T("timing_xlab"))
    ax.set_ylabel(T("timing_ylab_ecdf"))
    ax.set_title(T("timing_ecdf_title"))
    ax.set_ylim(0, 102)
    ax.grid(True, which="both", alpha=0.25)
    # Legend collected below for shared figure legend

    # Stats box — placed in the empty band between PID (~0.03 ms) and NMPC (~25 ms)
    # i.e., centre-left in axes coordinates where no curve passes.
    lines = []
    for lbl, st in [("NMPC (5 Hz)", ns), ("PID (50 Hz)", p50), ("PID (5 Hz)", p5)]:
        if st:
            lines += [
                f"── {lbl} ──",
                f"n        : {st['n']:,}",
                f"{T('stats_mean'):<9}: {st['mean']:.4f} ms",
                f"P99      : {st['p99']:.4f} ms",
                f"{T('stats_deadline_pct')}: {st['pct_ok']:.1f}%",
                "",
            ]
    if ns and p50:
        ratio = ns["mean"] / p50["mean"] if p50["mean"] > 0 else float("inf")
        lines.append(f"{T('stats_ratio')}: {ratio:.0f}×")
    ax.text(
        0.37, 0.04, "\n".join(lines), transform=ax.transAxes,
        fontsize=7.5, va="bottom", family="monospace",
        bbox=dict(boxstyle="round,pad=0.4", facecolor="white",
                  alpha=0.92, edgecolor="#bbbbbb"),
    )

    # Single shared legend centred below both panels
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center",
               bbox_to_anchor=(0.5, -0.04), ncol=4,
               fontsize=9, framealpha=0.9, edgecolor="#cccccc")
    fig.tight_layout(rect=[0, 0.08, 1, 0.93])
    p2 = os.path.join(out_dir, "thesis_solver_distribution.png")
    fig.savefig(p2, dpi=150, bbox_inches="tight")
    plt.close(fig)

    print(f"  thesis_solver_timeline.png")
    print(f"  thesis_solver_distribution.png")
    print(f"  thesis_solver_stats.csv")
    if ns:
        print(f"  → NMPC: n={ns['n']}, mean={ns['mean']:.1f} ms, "
              f"P99={ns['p99']:.1f} ms, {ns['pct_ok']:.1f}% within deadline")
    if p50:
        print(f"  → PID (50 Hz): n={p50['n']}, mean={p50['mean']:.4f} ms, "
              f"P99={p50['p99']:.4f} ms")
    if p5:
        print(f"  → PID (5 Hz):  n={p5['n']}, mean={p5['mean']:.4f} ms, "
              f"P99={p5['p99']:.4f} ms")


# --------------------------------------------------------------------------- #
#  Main
# --------------------------------------------------------------------------- #
def main():
    os.makedirs(OUTDIR, exist_ok=True)

    print("[thesis_analysis] Loading data...")
    t, ref_deg, controllers = load_data()
    print(f"  Controllers: {list(controllers)}")
    print(f"  Duration: {t[-1]:.0f} s,  samples: {len(t)}")

    print("[thesis_analysis] Computing full performance metrics...")
    full_metrics = compute_full_metrics(t, ref_deg, controllers)

    print("[thesis_analysis] Root cause quantification...")
    root_cause = root_cause_analysis(t, ref_deg, controllers, full_metrics)

    print("[thesis_analysis] Statistical significance tests...")
    stat_tests = statistical_tests(t, ref_deg, controllers)

    print("[thesis_analysis] Segment decomposition...")
    seg_data = compute_segments(t, ref_deg, controllers)

    print("[thesis_analysis] Generating figures...")
    generate_figures(t, ref_deg, controllers, full_metrics, seg_data, OUTDIR)

    print("[thesis_analysis] Depth channel...")
    ref_depth, depth_ctrl = load_depth_data()
    depth_rows = None
    if depth_ctrl:
        d_regimes, d_seg, depth_rows = compute_depth_metrics(t, ref_depth, depth_ctrl)
        generate_depth_figures(t, ref_depth, depth_ctrl, d_regimes, d_seg, OUTDIR)
        R.write_csv(depth_rows,
                    ["controller", "rmse_m", "transient_rmse_m", "settled_rmse_m",
                     "mae_m", "p95_m", "max_m"],
                    os.path.join(OUTDIR, "thesis_depth_metrics.csv"))
    else:
        print("  no depth columns in the CSVs — rerun run_remus100_comparison "
              "and compare_nmpc_patch to get the depth figures")

    print("[thesis_analysis] Writing CSV tables...")
    write_metric_csvs(full_metrics, seg_data, stat_tests, OUTDIR)

    print("[thesis_analysis] Writing Markdown report...")
    generate_report(t, ref_deg, controllers, full_metrics, root_cause, stat_tests,
                    seg_data, OUTDIR)

    print("[thesis_analysis] Generating solver timing figures...")
    generate_timing_figures(OUTDIR)

    # Console summary table
    print("\n" + "=" * 70)
    print("  HEADING RMSE SUMMARY (°)")
    print(f"  {'Controller':35s} {'Aggregate':>10s} {'Transient':>10s} {'Settled':>10s}")
    print("  " + "-" * 67)
    for name, fm in full_metrics.items():
        print(f"  {name:35s} "
              f"{fm['aggregate']['rmse']:>10.2f} "
              f"{fm['transient']['rmse']:>10.2f} "
              f"{fm['settled']['rmse']:>10.3f}")
    print("=" * 70)
    if depth_rows:
        print("\n  DEPTH RMSE SUMMARY (m)")
        print(f"  {'Controller':35s} {'Aggregate':>10s} {'Transient':>10s} {'Settled':>10s}")
        print("  " + "-" * 67)
        for r in depth_rows:
            print(f"  {r['controller']:35s} "
                  f"{r['rmse_m']:>10.3f} "
                  f"{r['transient_rmse_m']:>10.3f} "
                  f"{r['settled_rmse_m']:>10.4f}")
        print("=" * 70)
    if stat_tests:
        print("\n  STATISTICAL TESTS (per-segment MAE, n=9 segments)")
        for cmp in stat_tests:
            p = cmp.get("paired_t_p", float("nan"))
            d = cmp.get("cohen_dz", float("nan"))
            sig = "**" if isinstance(p, float) and not math.isnan(p) and p < 0.05 else "  "
            print(f"  {sig}{cmp['label_a']} vs {cmp['label_b']}: "
                  f"Δ={cmp['mean_diff']:.2f}°, "
                  f"CI=[{cmp.get('ci_low_95', float('nan')):.2f}, "
                  f"{cmp.get('ci_high_95', float('nan')):.2f}], "
                  f"t-p={p:.4f}, d_z={d:.3f}{sig}")

    print(f"\n[thesis_analysis] Done.  Output -> {OUTDIR}")
    print("  thesis_report.md")
    print("  thesis_full_metrics.csv")
    print("  thesis_stat_tests.csv")
    print("  thesis_regime_comparison.png")
    print("  thesis_error_ecdf.png")
    print("  thesis_segment_breakdown.png")
    print("  thesis_zoom_reversal.png")
    print("  thesis_zoom_depthcoupling.png")
    print("  thesis_mission_overview.png")
    print("  thesis_solver_timeline.png")
    print("  thesis_solver_distribution.png")
    print("  thesis_solver_stats.csv")


if __name__ == "__main__":
    main()
